apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      containers:
      - name: greetings-container
        image: localhost:5000/greetings-service
        ports:
        - containerPort: 5000

